// flytask-react/src/pages/PasswordRecovery.tsx
// PasswordRecovery.tsx
import React, { useState } from 'react';
import { useFormik } from 'formik';
import * as Yup from 'yup';
import chincheta from '../images/chincheta.png';
import { recoverPRequest } from '../api/recoverPasswordAPI';
import NewPasswordForm from '../components/NewPasswordForm';
import Notification from '../components/Notification';

const RecoverPSchema = Yup.object().shape({
  email: Yup.string().email('Invalid email').required('Required'),
});

const PasswordRecovery: React.FC = () => {
  const [showNewPasswordForm, setShowNewPasswordForm] = useState(false);
  const [notification, setNotification] = useState({
    message: 'Hello, this is a notification!',
    color: 'bg-green-500',
    showNotification: false
  });

  const setShowNotification = (show: boolean) => {
    setNotification({
      ...notification,
      showNotification: show,
    });
  };

  const formikRecover = useFormik({
    initialValues: {
      email: '',
    },
    validationSchema: RecoverPSchema,
    onSubmit: (values) => {
      console.log(values);
      recoverPRequest
        .recoverPassword(values.email)
        .then((response) => {
          if(response.status === 200){
            setNotification({
              message: 'Email sent!',
              color: 'bg-green-500',
              showNotification: true,
            });
            setShowNewPasswordForm(true); // Show the new password form on successful request
          }
        })
        .catch((error) => {
          setNotification({
            message: 'An error ocurred, try again!',
            color: 'bg-red-500',
            showNotification: true,
          });
        });
    },
  });

  return (
    <div className="flex flex-col justify-center items-center h-screen w-full md:bg-signup-bg md:bg-cover">
      <div className="relative md:h-fit md:border md:rounded-md md:p-8 md:w-2/4 md:shadow-lg md:bg-white xl:w-1/3">
        <h1 className='text-center font-bold text-lg'>{showNewPasswordForm ? 'Reset Your Password' : 'Forgot your password?'}</h1>
        <h1 className='text-center text-sm'>{showNewPasswordForm ? 'Enter your new password and the token you received' : 'Enter your email and receive a temporary access code'}</h1>
        <img
          src={chincheta}
          alt="Decorative"
          className="invisible absolute top-0 left-0 transform -translate-x-1/2 -translate-y-1/2 w-16 h-16 md:visible"
          style={{ transform: 'translate(-50%, -50%)' }}
        />
        {showNewPasswordForm ? (
          <NewPasswordForm/>
        ) : (
          <form onSubmit={formikRecover.handleSubmit} className="space-y-6 mt-2">
            <div>
              <label htmlFor="email" className="block text-sm font-medium text-gray-700">Email</label>
              <input
                id="email"
                type="email"
                {...formikRecover.getFieldProps('email')}
                className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              />
              {formikRecover.touched.email && formikRecover.errors.email ? (
                <div className="text-sm text-red-600">{formikRecover.errors.email}</div>
              ) : null}
            </div>
            <button type="submit" className="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
              Send!
            </button>
          </form>
        )}
      </div>
      <Notification
          message={notification.message}
          color={notification.color}
          showNotification={notification.showNotification}
          setShowNotification={setShowNotification}
        />
    </div>
  );
};

export default PasswordRecovery;

// flytask-vue/src/views/PasswordRecovery.vue
<template>
  <div
    class="flex flex-col justify-center items-center h-screen w-full md:bg-signup-background md:bg-cover"
  >
    <NewPasswordForm v-if="showNewPasswordForm" />
    <div
      v-else="!showNewPasswordForm"
      class="relative md:h-fit md:border md:rounded-md md:p-8 md:w-2/4 md:shadow-lg md:bg-white xl:w-1/3"
    >
      <h1 class="text-center font-bold text-lg">Forgot your password?</h1>
      <h1 class="text-center text-sm">
        Enter your email to receive a temporary access code and change your
        password
      </h1>
      <!-- Absolute positioned image -->
      <img
        src="@/assets/chincheta.png"
        class="invisible absolute top-0 left-0 transform -translate-x-1/2 -translate-y-1/2 w-16 h-16 md:visible"
        alt="Chincheta"
      />
      <Form
        :validation-schema="RecoverPasswordSchema"
        @submit="onSubmit"
        class="h-full w-full p-3 flex flex-col gap-2 items-center"
      >
        <div class="mb-4 w-full">
          <label for="email" class="block text-sm font-medium text-gray-700"
            >Email</label
          >
          <Field
            name="email"
            type="email"
            class="mt-1 block w-full p-2 border border-gray-300 shadow-sm bg-mint rounded-md focus:outline-none focus:ring-primary focus:border-primary"
          />
          <ErrorMessage name="email" class="text-red-500 text-sm mt-1" />
        </div>
        <button
          class="p-2 text-center bg-yellow rounded-md text-white w-full hover:bg-yellow-100"
        >
          Send
        </button>
      </Form>
    </div>
    <Notification
      :message="notificationMessage"
      :show="showNotification"
      :color="notificationColor"
    />
  </div>
</template>

<script>
import { Field, Form, ErrorMessage } from "vee-validate";
import * as yup from "yup";
import Notification from "@/components/feedback/Notification.vue";
import { recoverPRequest } from "@/api/recoverPassword";
import NewPasswordForm from "@/components/NewPasswordForm.vue";

const RecoverPasswordSchema = yup.object({
  email: yup
    .string()
    .email("Invalid email format")
    .required("Email is required"),
});

export default {
  name: "PasswordRecovery",
  components: {
    Form,
    Field,
    ErrorMessage,
    Notification,
    NewPasswordForm,
  },
  methods: {
    triggerNotification(message, color) {
      this.notificationMessage = message;
      this.notificationColor = color;
      this.showNotification = true;
      setTimeout(() => {
        this.showNotification = false;
      }, 3000); // Hide after 3 seconds
    },

    onSubmit(values) {
      console.log(values);
      this.isLoading = true;
      recoverPRequest
        .recoverPassword(values.email)
        .then((response) => {
          console.log(response);
          if (response.status === 200) {
            (this.showNewPasswordForm = true),
              this.triggerNotification("Email sent!", "bg-green-500");
            this.isLoading = false;
          }
        })
        .catch((error) => {
          console.log(error);
          this.triggerNotification(
            "An error has ocurred, please try again",
            "bg-red-500"
          );
          this.isLoading = false;
        });
    },
  },
  data() {
    return {
      RecoverPasswordSchema,
      showNotification: false,
      notificationMessage: "",
      notificationColor: "bg-red-600",
      isLoading: false,
      showNewPasswordForm: false,
    };
  },
};
</script>
