// flytask-react/src/pages/TaskBoard.tsx
import React, { useEffect, useState } from "react";
import {
  BsListUl,
  BsGrid3X3Gap,
} from "react-icons/bs";
import EmptyTaskboard from "./EmptyTaskboard";
import { getTasks } from "../api/getTasksAPI";
import ListView from "../components/ListView";
import KanBan from "../components/KanBan";

const TaskBoard: React.FC = () => {
  const [listMode, setListMode] = useState(false);
  const [kanBanMode, setKanbanMode] = useState(false);
  const [tasks, setTasks] = useState<any>(null)

  useEffect(() => {
    getTasks
      .getTasks()
      .then((response) => {
        console.log(response);
        let tasks = response.data.data;
        console.log(tasks);
        setTasks(tasks);
      })
      .catch((error) => {
        if(error){
          window.location.href = '/sign-in'
        }
      })
  }, []);

  const handleKanBanMode = () => {
    setKanbanMode(true)
    setListMode(false)
  }

  const handleListMode = () => {
    setListMode(true)
    setKanbanMode(false)
  }

  return (
    <div className="bg-slate-50 h-screen">
      {/* Top bar with options */}
      <div className="flex justify-between items-center w-full shadow-lg h-[10vh]">
        {/* Options list */}
        <ul className="flex w-full bg-slate-50">
          <li className="">
            <button className="text-gray-800 bg-slate-50 hover:bg-slate-100 p-5" onClick={handleListMode}>
              <BsListUl className="inline-block mr-2" />
              List
            </button>
          </li>
          <li className="">
            <button className="text-gray-800 bg-slate-50 hover:bg-slate-100 p-5" onClick={handleKanBanMode}>
              <BsGrid3X3Gap className="inline-block mr-2" />
              Group by Stage  
            </button>
          </li>
        </ul>
      </div>

      <div className="h-[90vh]">
        {tasks ? (listMode ? <ListView tasks={tasks}/> : kanBanMode ? <KanBan tasks={tasks}/> : <ListView tasks={tasks}/>) : <EmptyTaskboard/>}
      </div>
    </div>
  );
};

export default TaskBoard;

// flytask-vue/src/views/Taskboard.vue
<template>
  <div className="bg-slate-50 h-screen">
    <div
      className="flex justify-between items-center w-full shadow-lg h-[10vh]"
    >
      <ul className="flex w-full bg-slate-50">
        <li className="">
          <button
            @click="listmode"
            class="text-gray-800 bg-slate-50 hover:bg-slate-100 p-5"
          >
            <BsListUl className="inline-block mr-2" />
            List
          </button>
        </li>
        <li className="">
          <button
            @click="kanbanmode"
            class="text-gray-800 bg-slate-50 hover:bg-slate-100 p-5"
          >
            <BsGrid3X3Gap className="inline-block mr-2" />
            Group by Stage
          </button>
        </li>
      </ul>
    </div>
    <div className="h-[90vh]">
      <div v-if="taskData.length > 0">
        <div v-if="list">
            <ListView :tasks="taskData"/>
        </div>
        <div v-else="kanban">
            <KanbanView/>
        </div>
      </div>
      <div v-else="taskData.length = 0">
        <EmptyTaskboard/>
      </div>
    </div>
  </div>
</template>

<script>
import { getTasks } from "@/api/getTasksAPI";
import { ref } from "vue";
import EmptyTaskboard from "@/components/sections/EmptyTaskboard.vue"
import ListView from "@/components/sections/ListView.vue"
import KanbanView from "@/components/sections/KanbanView.vue"

const taskData = ref([]);
const list = false;
const kanban = false;

export default {
  data() {
    return {
      taskData,
      list,
      kanban,
    };
  },

  components: {
    EmptyTaskboard, 
    ListView,
    KanbanView 
  },

  methods: {
    listmode() {
      this.list = true;
      this.kanban = false;
      console.log(this.list);
      console.log(this.kanban);
    },

    kanbanmode() {
      this.list = false;
      this.kanban = true;
      console.log(this.list);
      console.log(this.kanban);
    },
  },

  created() {
    getTasks
      .getTasks()
      .then((response) => {
        console.log(response);
        let tasks = response.data.data;
        console.log(tasks);
        this.taskData = tasks;
      })
      .catch((error) => {
        if (error) {
           window.location.href = "/login";
        }
      });
  },
};
</script>
