// flytask-react/src/components/ListView.tsx
import React, { useState } from "react";
import { Task } from "../utils/types";
import AddTaskModal from "./modals/AddTaskModal";
import EditTaskModal from "./modals/EditTaskModal";
import {
  isoToYYYYMMDD,
  numberToStatusColorConverter,
  numberToStatusConverter,
} from "../utils/dataConversions";
import {BiArrowToRight, BiMoveHorizontal } from "react-icons/bi";
import { MdAddTask } from "react-icons/md";
import MoveTaskModal from "./modals/MoveTaskModal";

type ListViewProps = {
  tasks: Task[];
};

const ListView: React.FC<ListViewProps> = ({ tasks }) => {
  const [searchText, setSearchText] = useState("");
  const [selectedTask, setSelectedTask] = useState<Task | null>(null);
  const [addTaskModalIsOpen, setAddTaskModalIsOpen] = useState(false);
  const [editTaskModalIsOpen, setEditTaskModalIsOpen] = useState(false);
  const [moveTaskModalIsOpen, setMoveTaskModalIsOpen] = useState(false);

  const filteredTasks = tasks.filter((task) =>
    task.title.toLowerCase().includes(searchText.toLowerCase())
  );

  const openAddTaskModal = () => {
    setAddTaskModalIsOpen(true);
  };

  const closeAddTaskModal = () => {
    setAddTaskModalIsOpen(false);
  };

  const openMoveTaskModal = () => {
    setMoveTaskModalIsOpen(true);
  };

  const closeMoveTaskModal = () => {
    setMoveTaskModalIsOpen(false);
  };

  const openEditTaskModal = () => {
    setEditTaskModalIsOpen(true);
  };

  const closeEditTaskModal = () => {
    setEditTaskModalIsOpen(false);
  };

  const handleSelectedTask = (task: Task) => {
    setSelectedTask(task);
    openEditTaskModal()
  };

  const handleMoveTask = (task: Task) => {
    setSelectedTask(task); 
    openMoveTaskModal()
  }

  return (
    <div className="h-full flex justify-center items-center">
      <div className="h-4/5 w-11/12 bg-glacierWhite rounded-lg shadow-lg flex flex-col">
        <div className="h-fit flex justify-between p-3 gap-3">
          <input
            type="text"
            className="w-5/6 bg-mint rounded-md px-3 py-2"
            placeholder="Search..."
            value={searchText}
            onChange={(e) => setSearchText(e.target.value)}
          />
          <div className="w-1/6 flex gap-2">
            <button
              className="bg-yellow px-3 rounded-md text-white w-full flex justify-center items-center gap-2"
              onClick={openAddTaskModal}
            >
              Add Task
              <MdAddTask/>
            </button>
          </div>
        </div>
        <div className="h-4/5 p-3 overflow-y-auto flex flex-col gap-2">
          {/* List of tasks */}
          {filteredTasks.map((task) => (
            <div
              key={task.taskId}
              
            >
              {/* Render task details here */}
              <div className="w-full flex justify-between rounded-md py-1 shadow-md border border-mint">
                <div className="flex justify-between m-1 items-center w-1/2 hover:bg-mint hover:rounded-md hover:border-r-2 hover:border-primary" onClick={() => handleSelectedTask(task)}>
                <div className="flex flex-col w-1/2 p-2 gap-1 justify-start">
                  <h3 className="text-lg font-medium">{task.title}</h3>
                  <p className="text-gray-500">{task.description}</p>
                </div>
                  <p className="p-2 flex items-center gap-2 text-gray-500">Edit <BiArrowToRight/></p>
                </div>
                <div className="flex flex-col w-1/2 items-end gap-1 p-2">
                  <div className="flex flex-row w-full justify-end">
                    <p className="text-md font-medium rounded-md p-1 w-2/3 text-center">
                      Due: {isoToYYYYMMDD(task.dueDate)}
                    </p>
                    <p
                      className={`text-md font-medium p-1 rounded-md w-1/3 text-center ${numberToStatusColorConverter(
                        task.status
                      )}`}
                    >
                      {numberToStatusConverter(task.status)}
                    </p>
                  </div>
                  <button className="bg-primary text-white p-1 w-1/3 rounded-md hover:bg-gray-500 flex gap-1 items-center justify-center" onClick={() => handleMoveTask(task)}>
                    Move
                    <BiMoveHorizontal/>
                  </button>
                </div>
              </div>
              {/* Add more task details if needed */}
            </div>
          ))}
        </div>
      </div>
      {addTaskModalIsOpen && (
        <AddTaskModal closeAddTaskModal={closeAddTaskModal} />
      )}
      {editTaskModalIsOpen && selectedTask && (
        <EditTaskModal
          task={selectedTask}
          closeEditTaskModal={closeEditTaskModal}
        />
      )}
      {
        moveTaskModalIsOpen && selectedTask && (
          <MoveTaskModal closeMoveTaskModal={closeMoveTaskModal} task={selectedTask}/>
        )
      }
    </div>
  );
};

export default ListView;

// flytask-vue/src/components/sections/ListView.vue
<template>
  <div class="h-[90vh] flex justify-center items-center">
    <div
      class="h-4/5 w-11/12 bg-glacierWhite rounded-lg shadow-lg flex flex-col"
    >
      <div class="h-fit flex justify-between p-3 gap-3">
        <input
          type="text"
          class="w-5/6 bg-mint rounded-md px-3 py-2"
          placeholder="Search..."
          v-model="searchText"
        />
        <div class="w-1/6 flex gap-2">
          <button
            class="bg-yellow px-3 rounded-md text-white w-full flex justify-center items-center gap-2"
            @click="openAddTaskModal"
          >
            Add Task
          </button>
        </div>
      </div>
      <div class="h-full p-3 overflow-y-auto flex flex-col gap-2">
        <div v-for="task in filterTasks" :key="task.taskId">
          <div
            class="w-full flex justify-between rounded-md py-1 shadow-md border border-mint"
          >
            <div
              class="flex justify-between m-1 items-center w-1/2 hover:bg-mint hover:rounded-md hover:border-r-2 hover:border-primary"
              @click="handleEditTask(task)"
            >
              <div class="flex flex-col w-1/2 p-2 gap-1 justify-start">
                <h3 class="text-lg font-medium">{{ task.title }}</h3>
                <p class="text-gray-500">{{ task.description }}</p>
              </div>
              <p class="p-2 flex items-center gap-2 text-gray-500">Edit</p>
            </div>
            <div class="flex flex-col w-1/2 items-end gap-1 p-2">
              <div class="flex flex-row w-full justify-end">
                <p class="text-md font-medium rounded-md p-1 w-2/3 text-center">
                  Due: {{ isoToYYYYMMDD(task.dueDate) }}
                </p>
                <p
                  class="text-md font-medium p-1 rounded-md w-1/3 text-center"
                  :class="numberToStatusColorConverter(task.status)"
                >
                  {{ numberToStatusConverter(task.status) }}
                </p>
              </div>
              <button
                class="bg-primary text-white p-1 w-1/3 rounded-md hover:bg-gray-500 flex gap-1 items-center justify-center"
                @click="handleMoveTask(task)"
              >
                Move
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <EditTaskModal :isOpen="editTaskModalIsOpen" :task={selectedTask} @close="closeEditTaskModal"/>
    <AddTaskModal :isOpen="addTaskModalIsOpen" @close="closeAddTaskModal" />
    <MoveTaskModal :isOpen="moveTaskModalIsOpen" @close="closeMoveTaskModal" :task="selectedTask"/>
  </div>
</template>

<script>
import { ref, computed } from "vue";
import AddTaskModal from "@/components/modals/AddTaskModal.vue";
import EditTaskModal from "@/components/modals/EditTaskModal.vue";
import MoveTaskModal from "@/components/modals/MoveTaskModal.vue";
import {
  isoToYYYYMMDD,
  numberToStatusColorConverter,
  numberToStatusConverter,
} from "@/utils/dataConversions";


const searchText = ref("");
const selectedTask = ref(null);
const addTaskModalIsOpen = ref(false);
const editTaskModalIsOpen = ref(false);
const moveTaskModalIsOpen = ref(false);

const openAddTaskModal = () => {
  addTaskModalIsOpen.value = true;
};

const closeAddTaskModal = () => {
  addTaskModalIsOpen.value = false;
};

export default {
  components: {
    AddTaskModal,
    EditTaskModal, 
    MoveTaskModal
  },
  props: {
    tasks: {
      type: Array,
      required: true,
    },
  },
  methods: {
    handleEditTask(task) {
      selectedTask.value = task;
      this.openEditTaskModal()
    },
    handleMoveTask(task) {
      selectedTask.value = task;
      this.openMoveTaskModal()
    },
    openEditTaskModal() {
      editTaskModalIsOpen.value = true;
    },
    closeEditTaskModal() {
      editTaskModalIsOpen.value = false;
    },
    openMoveTaskModal() {
      moveTaskModalIsOpen.value = true;
    },
    closeMoveTaskModal() {
      moveTaskModalIsOpen.value = false;
    },
  },

  computed: {
    filterTasks() {
      console.log(this.tasks);
      return this.tasks.filter((task) =>
        task.title.toLowerCase().includes(searchText.value.toLowerCase())
      );
    },
  },
  data() {
    return {
      searchText,
      selectedTask,
      addTaskModalIsOpen,
      editTaskModalIsOpen,
      moveTaskModalIsOpen,
      openAddTaskModal,
      closeAddTaskModal,
      isoToYYYYMMDD,
      numberToStatusColorConverter,
      numberToStatusConverter,
    };
  },
};
</script>
