// flytask-vue/src/components/NewPasswordForm.vue
<template>
  <div
    class="relative md:h-fit md:border md:rounded-md md:p-8 md:w-2/4 md:shadow-lg md:bg-white xl:w-1/3"
  >
    <h1 class="text-center font-bold text-lg">We sent you an email</h1>
    <h1 class="text-center text-sm">Submit the form to change your password</h1>
    <!-- Absolute positioned image -->
    <img
      src="@/assets/chincheta.png"
      class="invisible absolute top-0 left-0 transform -translate-x-1/2 -translate-y-1/2 w-16 h-16 md:visible"
      alt="Chincheta"
    />

    <Form
      :validation-schema="NewPasswordSchema"
      @submit="onSubmit"
      class="h-full w-full p-3 flex flex-col gap-2 items-center"
    >
      <div class="mb-4 w-full">
        <label for="newPassword" class="block text-sm font-medium text-gray-700"
          >New Password</label
        >
        <Field
          name="newPassword"
          type="password"
          class="mt-1 block w-full p-2 border border-gray-300 shadow-sm bg-mint rounded-md focus:outline-none focus:ring-primary focus:border-primary"
        />
        <ErrorMessage name="newPassword" class="text-red-500 text-sm mt-1" />
      </div>
      <div class="mb-4 w-full">
        <label
          for="passwordConfirmation"
          class="block text-sm font-medium text-gray-700"
          >Confirm New Password</label
        >
        <Field
          name="passwordConfirmation"
          type="password"
          class="mt-1 block w-full p-2 border border-gray-300 shadow-sm bg-mint rounded-md focus:outline-none focus:ring-primary focus:border-primary"
        />
        <ErrorMessage
          name="passwordConmfirmation"
          class="text-red-500 text-sm mt-1"
        />
      </div>
      <div class="mb-4 w-full">
        <label for="token" class="block text-sm font-medium text-gray-700"
          >Token</label
        >
        <Field
          name="token"
          as="textarea"
          class="mt-1 block w-full p-2 border border-gray-300 shadow-sm bg-mint rounded-md focus:outline-none focus:ring-primary focus:border-primary"
        />
        <ErrorMessage name="token" class="text-red-500 text-sm mt-1" />
      </div>
      <button
        type="submit"
        :disabled="isLoading"
        class="p-2 text-center bg-yellow rounded-md text-white w-full hover:bg-yellow-100"
      >
        <span v-if="isLoading" class="flex items-center justify-center">
          Changing...
        </span>
        <span v-else>Change Password</span>
      </button>
    </Form>
    <Notification
      :message="notificationMessage"
      :show="showNotification"
      :color="notificationColor"
    />
  </div>
</template>

<script>
import { Field, Form, ErrorMessage } from "vee-validate";
import * as yup from "yup";
import Notification from "@/components/feedback/Notification.vue";
import { setNewPassword } from "@/api/newPasswordAPI";

export default {
  components: {
    Form,
    Field,
    ErrorMessage,
    Notification,
  },
  data() {
    name: "NewPasswordForm";
    return {
      NewPasswordSchema: yup.object({
        newPassword: yup.string().min(8).required(),
        passwordConfirmation: yup
          .string()
          .oneOf([yup.ref("newPassword"), null], "Passwords must match")
          .required(),
        token: yup.string().required(),
      }),
      showNotification: false,
      notificationMessage: "",
      notificationColor: "bg-red-600",
      isLoading: false,
      showNewPasswordForm: false,
    };
  },
  methods: {
    triggerNotification(message, color) {
      this.notificationMessage = message;
      this.notificationColor = color;
      this.showNotification = true;
      setTimeout(() => {
        this.showNotification = false;
      }, 3000); // Hide after 3 seconds
    },

    onSubmit(values) {
      console.log(values);
      this.isLoading = true;
      setNewPassword
        .setPassword(values)
        .then((response) => {
          console.log(response);
          if (response.status === 200) {
            this.triggerNotification(
              "Password changed successfully!",
              "bg-green-500"
            );
            this.isLoading = false;
            window.location.href = "/login"
          }
        })
        .catch((error) => {
          console.log(error);
          this.triggerNotification(
            "An error has occurred, please try again",
            "bg-red-500"
          );
          this.isLoading = false;
        });
    },
  },
};
</script>

// flytask-react/src/components/NewPasswordForm.tsx
// NewPasswordForm.tsx
import React from 'react';
import { useFormik } from 'formik';
import * as Yup from 'yup';
import { setNewPassword } from '../api/newPasswordAPI';

const NewPasswordSchema = Yup.object().shape({
  newPassword: Yup.string().min(8, 'Password is too short - should be 8 chars minimum.').required('Required'),
  passwordConfirmation: Yup.string()
    .oneOf([Yup.ref('newPassword')], 'Passwords must match')
    .required('Required'),
  token: Yup.string().required('Required'),
});

const NewPasswordForm: React.FC = () => {
  const formikNewPassword = useFormik({
    initialValues: {
      newPassword: '',
      passwordConfirmation: '',
      token: '',
    },
    validationSchema: NewPasswordSchema,
    onSubmit: (values) => {
        console.log(values);
        setNewPassword
            .setPassword(values)
            .then((response) => {
                console.log(response);
                if(response.status === 200){
                    window.location.href = "/react/sign-in"
                }
            })
            .catch((error) => {
                console.log(error); 
            })
    },
  });

  return (
    <form onSubmit={formikNewPassword.handleSubmit} className="space-y-6 mt-2">
      <div>
        <label htmlFor="newPassword" className="block text-sm font-medium text-gray-700">New Password</label>
        <input
          id="newPassword"
          type="password"
          {...formikNewPassword.getFieldProps('newPassword')}
          className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
        />
        {formikNewPassword.touched.newPassword && formikNewPassword.errors.newPassword ? (
          <div className="text-sm text-red-600">{formikNewPassword.errors.newPassword}</div>
        ) : null}
      </div>
      <div>
        <label htmlFor="passwordConfirmation" className="block text-sm font-medium text-gray-700">Confirm New Password</label>
        <input
          id="passwordConfirmation"
          type="password"
          {...formikNewPassword.getFieldProps('passwordConfirmation')}
          className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
        />
        {formikNewPassword.touched.passwordConfirmation && formikNewPassword.errors.passwordConfirmation ? (
          <div className="text-sm text-red-600">{formikNewPassword.errors.passwordConfirmation}</div>
        ) : null}
      </div>
      <div>
        <label htmlFor="token" className="block text-sm font-medium text-gray-700">Token</label>
        <textarea
          id="token"
          {...formikNewPassword.getFieldProps('token')}
          className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
        />
        {formikNewPassword.touched.token && formikNewPassword.errors.token ? (
          <div className="text-sm text-red-600">{formikNewPassword.errors.token}</div>
        ) : null}
      </div>
      <button type="submit" className="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
        Reset Password
      </button>
    </form>
  );
};

export default NewPasswordForm;
