// flytask-vue/src/components/feedback/Notification.vue
<template>
    <div v-if="show" :class="`fixed bottom-4 right-4 p-4 rounded text-white shadow-lg transition-opacity duration-300 ${color}`">
      {{ message }}
    </div>
  </template>
  
  <script>
  export default {
    props: {
      message: {
        type: String,
        required: true,
      },
      show: {
        type: Boolean,
        default: false,
      },
      color: {
        type: String,
        default: 'bg-red-600',
      },
    },
    data() {
      return {
        visible: false,
      };
    },
    watch: {
      show(newVal) {
        if (newVal) {
          this.visible = true;
          setTimeout(() => {
            this.visible = false;
          }, 10000); // Hide after 3 seconds
        }
      },
    },
  };
  </script>
  
  <style scoped>
  /* Additional styling if needed */
  </style>

// flytask-react/src/components/Notification.tsx
import React, { useEffect } from 'react';

interface NotificationProps {
  message: string;
  color: string;
  showNotification: boolean;
  setShowNotification: (show: boolean) => void;
}

const Notification: React.FC<NotificationProps> = ({ message, color, showNotification, setShowNotification }) => {
  useEffect(() => {
    if (showNotification) {
      const timer = setTimeout(() => {
        setShowNotification(false);
      }, 3000); // Hide after 3 seconds

      return () => clearTimeout(timer);
    }
  }, [showNotification, setShowNotification]);

  if (!showNotification) return null;

  return (
    <div className={`fixed bottom-4 right-4 p-4 rounded-md shadow-lg ${color}`}>
      <p className="text-white">{message}</p>
    </div>
  );
};

export default Notification;
