// flytask-react/src/components/modals/AddTaskModal.tsx
import { Field, Form, Formik } from "formik";
import { MdClose } from "react-icons/md";
import * as Yup from "yup";
import { createTask } from "../../api/createTaskAPI";
import { useState } from "react";
import Notification from "../Notification";

const validationSchema = Yup.object().shape({
  title: Yup.string().required("Task Name is required"),
  description: Yup.string().required("Description is required"),
  dueDate: Yup.date()
    .min(new Date(), "Due Date cannot be earlier than today")
    .required("Due Date is required"),
  userId: Yup.number().required(),
});

export const AddTaskModal: React.FC<{ closeAddTaskModal: () => void }> = ({
  closeAddTaskModal,
}) => {
  const idValue = localStorage.getItem("id");
  const userId: number = Number(idValue);

  const [notification, setNotification] = useState({
    message: "Hello, this is a notification!",
    color: "bg-green-500",
    showNotification: false,
  });

  const setShowNotification = (show: boolean) => {
    setNotification({
      ...notification,
      showNotification: show,
    });
  };

  return (
    <div className="fixed inset-0 bg-gray-900 bg-opacity-50 flex justify-center items-center z-50">
      <div className="relative bg-white rounded-lg shadow-lg overflow-hidden h-fit p-8 w-5/6 md:w-2/3 lg:w-1/3">
        <button
          className="absolute top-2 right-2 text-gray-700"
          onClick={closeAddTaskModal}
        >
          <MdClose size={24} />
        </button>
        <h2 className="text-2xl font-bold mb-4">Create new task</h2>
        <Formik
          initialValues={{
            title: "",
            description: "",
            dueDate: "",
            userId: userId,
          }}
          validationSchema={validationSchema}
          onSubmit={(values) => {
            console.log(values);

            createTask
              .createTask(values)
              .then((response) => {
                if (response.status === 200) {
                  setNotification({
                    message: 'Task created!',
                    color: 'bg-green-500',
                    showNotification: true,
                  });
                  window.location.reload();
                }
              })
              .catch((error) => {
                setNotification({
                  message: 'An error has ocurred, try again!',
                  color: 'bg-red-500',
                  showNotification: true,
                });
              });
            closeAddTaskModal();
          }}
        >
          {({ errors, touched }) => (
            <Form>
              <div className="mb-4">
                <label
                  htmlFor="taskName"
                  className="block text-gray-700 font-bold mb-2"
                >
                  Task Name:
                </label>
                <Field
                  type="text"
                  id="title"
                  name="title"
                  className="w-full p-2 border border-primary bg-mint rounded-md shadow-md"
                />
                {errors.title && touched.title && (
                  <div className="text-red-500">{errors.title}</div>
                )}
              </div>
              <div className="mb-4">
                <label
                  htmlFor="description"
                  className="block text-gray-700 font-bold mb-2"
                >
                  Description:
                </label>
                <Field
                  as="textarea"
                  id="description"
                  name="description"
                  className="w-full p-2 border border-primary bg-mint  rounded-md shadow-md"
                  rows={4}
                />
                {errors.description && touched.description && (
                  <div className="text-red-500">{errors.description}</div>
                )}
              </div>
              <div className="mb-4">
                <label
                  htmlFor="dueDate"
                  className="block text-gray-700 font-bold mb-2"
                >
                  Due Date:
                </label>
                <Field
                  type="date"
                  id="dueDate"
                  name="dueDate"
                  className="w-full p-2 border border-primary bg-mint  rounded-md shadow-md"
                />
                {errors.dueDate && touched.dueDate && (
                  <div className="text-red-500">{errors.dueDate}</div>
                )}
              </div>
              <button
                type="submit"
                className="w-full bg-yellow hover:bg-yellow text-white py-2 px-4 rounded-md shadow-md"
              >
                Create
              </button>
            </Form>
          )}
        </Formik>
      </div>
      <Notification
          message={notification.message}
          color={notification.color}
          showNotification={notification.showNotification}
          setShowNotification={setShowNotification}
        />
    </div>
  );
};

export default AddTaskModal;

// flytask-vue/src/components/modals/AddTaskModal.vue
<template>
  <transition name="modal">
    <div
      class="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50 z-50"
      v-if="isOpen"
    >
      <div
        class="bg-white rounded-lg shadow-lg overflow-hidden h-fit p-8 w-5/6 md:w-2/3 lg:w-1/3"
      >
        <header class="flex justify-between items-center mb-3">
          <p class="font-bold">Add Task</p>
          <button @click="closeModal" class="text-gray-700">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-6 w-6"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        </header>
        <div class="h-fit w-full flex flex-col justify-center items-center">
          <Form
            :validation-schema="AddTaskSchema"
            @submit="onSubmit"
            class="w-4/5 flex flex-col justify-evenly items-center"
          >
            <div class="mb-4 w-full">
              <label for="title" class="block text-sm font-medium text-gray-700"
                >title</label
              >
              <Field
                name="title"
                class="mt-1 block w-full p-2 border border-gray-300 shadow-sm bg-mint rounded-md focus:outline-none focus:ring-primary focus:border-primary"
              />
              <ErrorMessage name="title" class="text-red-500 text-sm mt-1" />
            </div>
            <div class="mb-4 w-full">
              <label
                for="description"
                class="block text-sm font-medium text-gray-700"
                >Description</label
              >
              <Field
                name="description"
                class="mt-1 block w-full p-2 border border-gray-300 rounded-md shadow-sm bg-mint focus:outline-none focus:ring-primary focus:border-primary"
              />
              <ErrorMessage
                name="description"
                class="text-red-500 text-sm mt-1"
              />
            </div>
            <div class="mb-4 w-full">
              <label
                for="dueDate"
                class="block text-sm font-medium text-gray-700"
                >Due date</label
              >
              <Field
                name="dueDate"
                type="date"
                class="mt-1 block w-full p-2 border border-gray-300 rounded-md shadow-sm bg-mint focus:outline-none focus:ring-primary focus:border-primary"
              />
              <ErrorMessage name="dueDate" class="text-red-500 text-sm mt-1" />
            </div>
            <button
              :disabled="isLoading"
              type="submit"
              class="p-2 text-center bg-yellow rounded-md text-white w-full hover:bg-yellow-100 mt-2"
            >
              <span v-if="isLoading">
                <p>Processing...</p>
              </span>
              <span v-if="!isLoading">
                <p>Add</p>
              </span>
            </button>
          </Form>
        </div>
      </div>
      <Notification
        :message="notificationMessage"
        :show="showNotification"
        :color="notificationColor"
      />
    </div>
  </transition>
</template>

<script>
import { Field, Form, ErrorMessage } from "vee-validate";
import * as yup from "yup";
import { createTask } from "@/api/createTaskAPI";
import Notification from "@/components/feedback/Notification.vue";

const AddTaskSchema = yup.object().shape({
  title: yup.string().required("Task Name is required"),
  description: yup.string().required("Description is required"),
  dueDate: yup
    .date()
    .min(new Date(), "Due Date cannot be earlier than today")
    .required("Due Date is required"),
});

export default {
  props: {
    isOpen: {
      type: Boolean,
      required: true,
    },
  },
  methods: {
    closeModal() {
      this.$emit("close");
    },

    triggerNotification(message, color) {
      this.notificationMessage = message;
      this.notificationColor = color;
      this.showNotification = true;
      setTimeout(() => {
        this.showNotification = false;
      }, 3000); // Hide after 3 seconds
    },

    onSubmit(values) {
      this.isLoading = true;
      let userId = localStorage.getItem("id");
      createTask
        .createTask(values, userId)
        .then((response) => {
          if (response.status === 200) {
            this.triggerNotification("Task created!", "bg-green-500");
            this.isLoading = false;
            window.location.reload()
          }
        })
        .catch((error) => {
          this.triggerNotification(
            "An error has ocurred, please try again",
            "bg-red-500"
          );
          this.isLoading = false;
        });
    },
  },
  data() {
    return {
      AddTaskSchema,
      showNotification: false,
      notificationMessage: "",
      notificationColor: "bg-red-600",
      isLoading: false,
    };
  },
  components: {
    Form,
    Field,
    ErrorMessage,
    Notification,
  },
};
</script>
