// flytask-react/src/components/modals/EditTaskModal.tsx
import React, { useState } from "react";
import { Field, Form, Formik } from "formik";
import { MdClose } from "react-icons/md";
import * as Yup from "yup";
import { Task } from "../../utils/types";
import { editTask } from "../../api/editTaskAPI";
import { yyyymmddToISO } from "../../utils/dataConversions";
import Notification from "../Notification";

const validationSchema = Yup.object().shape({
  title: Yup.string().required("Task Name is required"),
  description: Yup.string().required("Description is required"),
  dueDate: Yup.date()
    .min(new Date(), "Due Date cannot be earlier than today")
    .required("Due Date is required"),
  taskId: Yup.number().required(),
});

type EditTaskModalProps = {
  closeEditTaskModal: () => void;
  task: Task;
};

export const EditTaskModal: React.FC<EditTaskModalProps> = ({
  closeEditTaskModal,
  task,
}) => {
  const idValue = localStorage.getItem("id");
  const userId: number = Number(idValue);

  const [notification, setNotification] = useState({
    message: 'Hello, this is a notification!',
    color: 'bg-green-500',
    showNotification: false
  });

  const setShowNotification = (show: boolean) => {
    setNotification({
      ...notification,
      showNotification: show,
    });
  };

  return (
    <div className="fixed inset-0 bg-gray-900 bg-opacity-50 flex justify-center items-center z-50">
      <div className="bg-white rounded-lg shadow-lg overflow-hidden h-fit p-8 w-5/6 md:w-2/3 lg:w-2/3 xl:w-1/3 relative">
        <button
          className="absolute top-2 right-2 text-gray-700"
          onClick={closeEditTaskModal}
        >
          <MdClose size={24} />
        </button>
        <h2 className="text-2xl font-bold mb-4">Edit task</h2>
        <Formik
          initialValues={{
            title: task.title,
            description: task.description,
            dueDate: task.dueDate.split("T")[0],
             // to format as YYYY-MM-DD
            taskId: task.taskId
          }}
          validationSchema={validationSchema}
          onSubmit={(values) => {
            editTask
              .editTask(
                {
                  title: values.title,
                  description: values.description,
                  dueDate: yyyymmddToISO(values.dueDate),
                },
                task.taskId
              )
              .then((response) => {
                if (response.status === 200) {
                  setNotification({
                    message: 'Task updated!',
                    color: 'bg-green-500',
                    showNotification: true,
                  });
                 window.location.reload()
                }
              })
              .catch((error) => {
                setNotification({
                  message: 'An error has ocurred, try again!',
                  color: 'bg-red-500',
                  showNotification: true,
                });
              });
          }}
        >
          {({ errors, touched }) => (
            <Form>
              <div className="mb-4">
                <label
                  htmlFor="taskName"
                  className="block text-gray-700 font-bold mb-2"
                >
                  Task Name:
                </label>
                <Field
                  type="text"
                  id="title"
                  name="title"
                  className="w-full p-2 border border-primary bg-mint rounded-md shadow-md"
                />
                {errors.title && touched.title && (
                  <div className="text-red-500">{errors.title}</div>
                )}
              </div>
              <div className="mb-4">
                <label
                  htmlFor="description"
                  className="block text-gray-700 font-bold mb-2"
                >
                  Description:
                </label>
                <Field
                  as="textarea"
                  id="description"
                  name="description"
                  className="w-full p-2 border border-primary bg-mint rounded-md shadow-md"
                  rows={4}
                />
                {errors.description && touched.description && (
                  <div className="text-red-500">{errors.description}</div>
                )}
              </div>
              <div className="mb-4">
                <label
                  htmlFor="dueDate"
                  className="block text-gray-700 font-bold mb-2"
                >
                  Due Date:
                </label>
                <Field
                  type="date"
                  id="dueDate"
                  name="dueDate"
                  className="w-full p-2 border border-primary bg-mint rounded-md shadow-md"
                />
                {errors.dueDate && touched.dueDate && (
                  <div className="text-red-500">{errors.dueDate}</div>
                )}
              </div>
              <button
                type="submit"
                className="w-full bg-yellow hover:bg-yellow text-white py-2 px-4 rounded-md shadow-md"
              >
                Update task
              </button>
            </Form>
          )}
        </Formik>
      </div>
      <Notification
          message={notification.message}
          color={notification.color}
          showNotification={notification.showNotification}
          setShowNotification={setShowNotification}
        />
    </div>
  );
};

export default EditTaskModal;

// flytask-vue/src/components/modals/EditTaskModal.vue
<template>
  <transition name="modal">
    <div
      class="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50 z-50"
      v-if="isOpen"
    >
      <div
        class="bg-white rounded-lg shadow-lg overflow-hidden h-fit p-8 w-5/6 md:w-2/3 lg:w-1/3"
      >
        <header class="flex justify-between items-center">
          <p class="font-bold">Edit task</p>
          <button @click="closeModal" class="text-gray-700">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-6 w-6"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        </header>
        <div class="p-4">
          <slot></slot>
        </div>
        <div class="h-fit w-full flex flex-col justify-center items-center">
          <Form
            :validation-schema="EditTaskSchema"
            @submit="onSubmit"
            class="h-fit w-full flex flex-col justify-evenly items-center"
            v-slot="{ errors }"
          >
            <div class="mb-4 w-full">
              <label for="title" class="block text-sm font-medium text-gray-700"
                >Title</label
              >
              <Field
                name="title"
                :value="task.title"
                class="mt-1 block w-full p-2 border border-gray-300 shadow-sm bg-mint rounded-md focus:outline-none focus:ring-primary focus:border-primary"
              />
              <ErrorMessage name="title" class="text-red-500 text-sm mt-1" />
            </div>
            <div class="mb-4 w-full">
              <label
                for="description"
                class="block text-sm font-medium text-gray-700"
                >Description</label
              >
              <Field
                name="description"
                :value="task.description"
                class="mt-1 block w-full p-2 border border-gray-300 rounded-md shadow-sm bg-mint focus:outline-none focus:ring-primary focus:border-primary"
              />
              <ErrorMessage
                name="description"
                class="text-red-500 text-sm mt-1"
              />
            </div>
            <div class="mb-4 w-full">
              <label
                for="dueDate"
                class="block text-sm font-medium text-gray-700"
                >Due date</label
              >
              <Field
                name="dueDate"
                type="date"
                :value="formatDate()"
                class="mt-1 block w-full p-2 border border-gray-300 rounded-md shadow-sm bg-mint focus:outline-none focus:ring-primary focus:border-primary"
              />
              <ErrorMessage name="dueDate" class="text-red-500 text-sm mt-1" />
            </div>
            <button
              :disabled="isLoading"
              type="submit"
              class="p-2 mt-2 text-center bg-yellow rounded-md text-white w-full hover:bg-yellow-100"
            >
              <span v-if="isLoading">
                <p>Processing...</p>
              </span>
              <span v-if="!isLoading">
                <p>Update</p>
              </span>
            </button>
          </Form>
        </div>
      </div>
      <Notification
        :message="notificationMessage"
        :show="showNotification"
        :color="notificationColor"
      />
    </div>
  </transition>
</template>

<script>
import { Field, Form, ErrorMessage } from "vee-validate";
import * as yup from "yup";
import { editTask } from "@/api/editTaskAPI";
import { isoToYYYYMMDD } from "@/utils/dataConversions";
import Notification from "@/components/feedback/Notification.vue";

const EditTaskSchema = yup.object().shape({
  title: yup.string().required("Task Name is required"),
  description: yup.string().required("Description is required"),
  dueDate: yup
    .date()
    .min(new Date(), "Due Date cannot be earlier than today")
    .required("Due Date is required"),
});

export default {
  props: {
    isOpen: {
      type: Boolean,
      required: true,
    },
    task: {
      type: Object,
      required: true,
    },
  },
  data() {
    return {
      EditTaskSchema,
      showNotification: false,
      notificationMessage: "",
      notificationColor: "bg-red-600",
      isLoading: false,
    };
  },
  methods: {
    closeModal() {
      this.$emit("close");
    },

    triggerNotification(message, color) {
      this.notificationMessage = message;
      this.notificationColor = color;
      this.showNotification = true;
      setTimeout(() => {
        this.showNotification = false;
      }, 3000); // Hide after 3 seconds
    },

    onSubmit(values) {
      this.isLoading = true;
      let taskId = this.task.taskId;
      editTask
        .editTask(values, taskId)
        .then((response) => {
          if (response.status === 200) {
            this.triggerNotification("Task updated!", "bg-green-500");
            this.isLoading = false;
            window.location.reload();
          }
        })
        .catch((error) => {
          this.triggerNotification(
            "An error has ocurred, please try again",
            "bg-red-500"
          );
          this.isLoading = false;
        });
    },
    formatDate() {
      console.log(this.task);
      return isoToYYYYMMDD(this.task.dueDate);
    },
  },

  components: {
    Form,
    Field,
    ErrorMessage,
    Notification,
  },
};
</script>
