// flytask-vue/src/views/Login.vue
<template>
  <div
    class="h-screen w-full bg-signup-background bg-cover flex justify-center items-center"
  >
    <div
      class="relative bg-slate-50 p-8 rounded-lg shadow-md w-full max-w-md h-3/5 shadow-lg"
    >
      <h1 class="text-center font-bold text-lg">Welcome</h1>
      <h1 class="text-center text-sm">
        FlyTask: where your productivity takes flight!
      </h1>
      <!-- Absolute positioned image -->
      <img
        src="@/assets/chincheta.png"
        class="absolute top-0 left-0 transform -translate-x-1/2 -translate-y-1/2 w-24 h-24"
        alt="Chincheta"
      />
      <Form
        :validation-schema="loginSchema"
        @submit="onSubmit"
        class="h-full w-full flex flex-col gap-2 items-center"
      >
        <div class="mb-4 w-full">
          <label for="email" class="block text-sm font-medium text-gray-700"
            >Email</label
          >
          <Field
            name="email"
            type="email"
            class="mt-1 block w-full p-2 border border-gray-300 shadow-sm bg-mint rounded-md focus:outline-none focus:ring-primary focus:border-primary"
          />
          <ErrorMessage name="email" class="text-red-500 text-sm mt-1" />
        </div>
        <div class="mb-4 w-full">
          <label for="password" class="block text-sm font-medium text-gray-700"
            >Password</label
          >
          <Field
            name="password"
            type="password"
            class="mt-1 block w-full p-2 border border-gray-300 rounded-md shadow-sm bg-mint focus:outline-none focus:ring-primary focus:border-primary"
          />
          <ErrorMessage name="password" class="text-red-500 text-sm mt-1" />
        </div>
        <button
          class="p-2 text-center bg-yellow rounded-md text-white w-full hover:bg-yellow-100"
        >
          Sign in
        </button>
      </Form>
    </div>
  </div>
</template>

<script>
import { Field, Form, ErrorMessage } from "vee-validate";
import * as yup from "yup";
import { loginUser } from "@/api/loginAPI";

const loginSchema = yup.object({
  email: yup
    .string()
    .email("Invalid email format")
    .required("Email is required"),
  password: yup
    .string()
    .required("Password is required")
    .min(8, "Password must be at least 8 characters long")
    .matches(/[A-Z]/, "Password must contain at least one uppercase letter")
    .matches(/[a-z]/, "Password must contain at least one lowercase letter")
    .matches(
      /[!@#$%^&*(),.?":{}|<>]/,
      "Password must contain at least one special character"
    ),
});

export default {
  name: "Login",
  components: {
    Form,
    Field,
    ErrorMessage,
  },
  methods: {
    onSubmit(values) {
      console.log(values);
      loginUser
        .login(values)
        .then((response) => {
          console.log(response);
          let token = response.data.token;
          if (token) {
            localStorage.setItem("name", response.data.name);
            localStorage.setItem("token", token);
            localStorage.setItem("id", response.data.id);
            window.location.href = "/board";
          }
        })
        .catch((error) => {
          console.log(error);
        });
    },
  },
  data() {
    return {
      loginSchema,
    };
  },
};
</script>

// app-with-modules/src/app/features/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  title = 'Login Component';
  email: string = '';
  password: string = '';

  constructor(private router: Router) {}

  onLogin() {

    this.router.navigate(['/etask']);
  }
}

<html>
<head>
    <title>FlyTask Login</title>
    <style>
        body {
            font-family: 'Inter', sans-serif;
            background-color: #f7f7f7;
            /*background-image: url('');*/
        }
    </style>
</head>
<body>
    <div class="min-h-screen flex items-center justify-center">
        <div class="bg-white p-8 rounded-lg shadow-lg max-w-sm">
          <div class="mb-4">
            <h1 class="text-2xl font-semibold">Welcome</h1>
            <p class="text-gray-600">FlyTask: Where your productivity takes flight!</p>
          </div>
          <form (ngSubmit)="onLogin()">
            <div class="mb-4">
              <label for="email" class="block text-gray-700 text-sm font-medium mb-2">Email</label>
              <input type="email" id="email" placeholder="example@uca.edu.sv" class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-pink-500">
            </div>
            <div class="mb-6">
              <label for="password" class="block text-gray-700 text-sm font-medium mb-2">Password</label>
              <input type="password" id="password" placeholder="******************" class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-pink-500">
            </div>
            <div class="mb-4">
              <button type="submit" class="w-full bg-pink-500 hover:bg-pink-600 text-white font-medium py-2 px-4 rounded focus:outline-none focus:shadow-outline">Login</button>
            </div>
          </form>
          <div class="text-center text-sm text-gray-500">
            <a routerLink="/npass" class="text-pink-500 hover:text-pink-600">Forgot my password</a>
          </div>
          <div class="text-center mt-6">
            <p class="text-gray-600">Don't have an account? <a routerLink="/signup" class="text-pink-500 hover:text-pink-600">Signup here</a></p>
          </div>
        </div>
      </div>
      
</body>
</html>
